title       = "acl"
baseURL     = "https://aclanthology-cli.tamnd.com/"
description = "Browse ACL Anthology NLP/CL research papers"
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/aclanthology-cli"
